package service;

import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2016-03-17T15:28:46.471+08:00
 * Generated source version: 3.0.0-milestone2
 * 
 */
@WebService(targetNamespace = "http://service/", name = "ws")
@XmlSeeAlso({ObjectFactory.class})
public interface Ws {

    @RequestWrapper(localName = "sayHello", targetNamespace = "http://service/", className = "service.SayHello")
    @WebMethod
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://service/", className = "service.SayHelloResponse")
    public void sayHello();
}
