package service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;
import service.Ws;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2016-03-17T15:28:46.498+08:00
 * Generated source version: 3.0.0-milestone2
 * 
 */
@WebServiceClient(name = "HelloWord", 
                  wsdlLocation = "http://localhost/ws/helloword?wsdl",
                  targetNamespace = "http://impl.service/") 
public class HelloWord extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.service/", "HelloWord");
    public final static QName HelloWordImplPort = new QName("http://impl.service/", "HelloWordImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost/ws/helloword?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloWord.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost/ws/helloword?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloWord(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloWord(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWord() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HelloWord(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HelloWord(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HelloWord(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns Ws
     */
    @WebEndpoint(name = "HelloWordImplPort")
    public Ws getHelloWordImplPort() {
        return super.getPort(HelloWordImplPort, Ws.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Ws
     */
    @WebEndpoint(name = "HelloWordImplPort")
    public Ws getHelloWordImplPort(WebServiceFeature... features) {
        return super.getPort(HelloWordImplPort, Ws.class, features);
    }

}
